### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [beaupreda/semi-global-matching#1]
When using your example:
`python sgm.py --left cones/im2.png --right cones/im6.png --left_gt cones/disp2.png --right_gt cones/disp6.png --output disparity_map.png --disp 64 --images False --eval True`
I get the following logs:

> Loading images...
Starting cost computation...
        Computing left and right census...Traceback (most recent call last):
  File "sgm.py", line 431, in <module>
    sgm()
  File "sgm.py", line 392, in sgm
    left_cost_volume, right_cost_volume = compute_costs(left, right, parameters, save_images)
  File "sgm.py", line 261, in compute_costs
    left_img_census[y, x] = np.uint8(left_census)
OverflowError: Python int too large to convert to C long

**Comment by beaupreda** [comment]
Are you using Windows? I am not able to reproduce this bug on my Linux machine, so if you could test whether it works for you on Linux, I would appreciate. I will look into this bug and come up with a solution!

**Comment by RaphaelRoyerRivard** [comment]
I am indeed working on Windows and I don't currently have an easy way of testing it on Linux.

**Comment by RaphaelRoyerRivard** [comment]
I changed the uint8 casts to unit64 (which is probably not the right fix) and got the following error:

> Applying median filter...
Traceback (most recent call last):
  File "sgm.py", line 432, in <module>
    sgm()
  File "sgm.py", line 413, in sgm
    left_disparity_map = cv2.medianBlur(left_disparity_map, parameters.bsize[0])
cv2.error: OpenCV(4.2.0) C:/projects/opencv-python/opencv/modules/imgproc/src/median_blur.simd.hpp:975: error: (-210:Unsupported format or combination of formats)  in function 'cv::opt_AVX2::medianBlur'

**Comment by beaupreda** [comment]
I fixed the bug and tested it on a Windows machine (basically, a Long type on Windows was considered 32 bits while Linux considered it as 64 bits). If you confirm that everything is working on your end, I will close this issue!

**Comment by RaphaelRoyerRivard** [comment]
It works indeed! Thank you for the fix.
However, I have a question about the code so I'll open up a new issue.
