### ISSUE TITLE
How to change the cost function

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [beaupreda/semi-global-matching#2]
I need to test 2 different descriptors (HOG and BRIEF) for my computer vision class and I'm trying to find where they could be used in the code. I believe it would be in the `compute_costs` function, where the census transform is used (this seems to be very similar to BRIEF).

Am I correct?

**Comment by beaupreda** [comment]
Yes, you will need to modify the compute_costs function. (I am your TA by the way!)

**Comment by RaphaelRoyerRivard** [comment]
Hahaha indeed, I haven't realized!
