### ISSUE TITLE
Recall function is wrong

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [beaupreda/semi-global-matching#3]
The in the following lines of the `get_recall` method,
```
gt = np.int16(gt / np.amax(gt) * float(args.disp))
disparity = np.int16(np.float32(disparity) / np.amax(disparity) * float(args.disp))
```

the `np.amax(...)` functions should be replaced with 255.0.

Using the maximum disparity found makes no sense because it influences the value of all the other disparities.

**Comment by beaupreda** [comment]
Yes, you are correct, it is now fixed. Thank you!
