### ISSUE TITLE
Why the processing time is so long?

### ISSUE THREAD

**Issue by Tina1994** [beaupreda/semi-global-matching#4]
First thanks for provide the code. 
I use the code to generate disparity map with with KITTI RGB stereo images, and the processing time is nearly 1800 seconds for only one pair images. 
The result of stereo matching is good, but why the processing is so long? Is anywhere wrong?

**Comment by beaupreda** [comment]
KITTI images are quite big so it is normal that it takes a lot of time! Check your memory consumption also, I would be surprise if the program was taking a lot of it. If you want the processing to go faster, I suggest either resizing the images so they are smaller, or maybe use a C++ or CUDA implementation which are much faster than this Python program! (There are links to other implementations in the README).

**Comment by Tina1994** [comment]
> KITTI images are quite big so it is normal that it takes a lot of time! Check your memory consumption also, I would be surprise if the program was taking a lot of it. If you want the processing to go faster, I suggest either resizing the images so they are smaller, or maybe use a C++ or CUDA implementation which are much faster than this Python program! (There are links to other implementations in the README).

Thanks for you apply, I tried the modified code built in python-opencv and found that the processing time is less than 30 ms for one pair kitti image. But the result is not satisfactory for that there is no disparity in the the first 'num_disparity' column, which is worse than the code you supply.  So I doubt that the code you supply could also achieve a faster processing time.

**Comment by beaupreda** [comment]
Yes, I doubt it as well. The goal of this project was more of a learning experience, so if you want better performance (both visually and in compute time), you can check for C++ of CUDA solutions!
