### ISSUE TITLE
Can't find the output image

### ISSUE THREAD

**Issue by niklausfangtasia** [beaupreda/semi-global-matching#5]
Hey, I've tried your code with the example command. And I can't find this output image **disparity_map.png**, but **left_disparity_map.png** and **right_disparity_map.png**.
Besides, I wanna ask, are these two pictures under cones folder (disp2.png and disp6.png) generated **before** the command is executed? Because I changed the command python3 sgm.py --left cones/im2.png --right cones/im6.png --left_gt cones/**dis2.png** --right_gt cones/**dis6.png** --output disparity_map.png --disp 64 --images False --eval True and could also be executed successfully without the output image.

**Comment by beaupreda** [comment]
There are actually two output images (for the left and right disparity map). The name you give in the command is appended to "left_" and "right_" to give both disparity maps. The images in the cones folder are from a dataset as an example, so they are never generated.
