### ISSUE TITLE
Finding Disparity Range

### ISSUE THREAD

**Issue by bricksaver** [beaupreda/semi-global-matching#6]
It's taking me quite a long time to look for the disparity range value to set in the command line to get a smooth disparity output from the code. Is there a good way to figure out what disparity range to set the "--disp" parameter to?

**Comment by beaupreda** [comment]
Some datasets specify the disparity range, but if you are working with your own dataset and do not know the value, you will need to test different values! (Maybe there is a way, but I am not aware of it at the moment!)
